### ISSUE TITLE
Subplots with plotly express

### ISSUE THREAD

**Issue by cyonghui81** [plotly/plotly_express#83] opened 2019-05-15 03:12 UTC
Can i do subplots, where each subplot is a time series chart using plotly express ?

**Comment by nicolaskruchten** [comment] 2019-05-20 19:02
Yes, [you can use `facet_row` and `facet_col`](https://plotly.com/python/facet-plots/) on any 2d-cartesian plot, including those with date axes.

**Comment by briangottfried** [comment] 2019-06-18 14:15
@nicolaskruchten, is it possible to make subplots where you are combine two charts created with plotly express? 
Something like this: 
![image](https://user-images.githubusercontent.com/10342878/59691972-ffe5cd00-91b1-11e9-805e-2ff1dd14ba9c.png)

**Comment by nicolaskruchten** [comment] 2019-06-20 13:10
@briangottfried there's no easy way to compose like this at the moment but we're working on it! See this issue: https://github.com/plotly/plotly.py/issues/2647

**Comment by floriangehrig** [comment] 2019-07-19 06:27
Is there any update on this yet?

**Comment by nicolaskruchten** [comment] 2019-07-19 12:16
There's no news on composing PX charts like this, but Plotly.py v4 came out this week, and it features a new and much-easier-to-use subplots system! Check it out here https://plot.ly/python/subplots/

Also, as of this week, Plotly Express is now part of Plotly.py (accessible as `plotly.express`) and is interoperable with the `make_subplots` function described in the link above.

**Comment by AliceMarb** [comment] 2019-07-19 18:42
Is it possible to use make_subplots for maps in plotly express? I currently have a plotly express map with a slider for dates, but would rather have multiple subplots of the different dates.

**Comment by nicolaskruchten** [comment] 2019-07-19 18:51
[You can use `make_subplots` on maps](https://plotly.com/python/subplots/) but Plotly Express doesn't support `facet_row` or `facet_col` on map-like traces just yet. Coming soon though!

See this issue: https://github.com/plotly/plotly.py/issues/2646

**Comment by AliceMarb** [comment] 2019-07-19 19:05
Wait sorry could you clarify for me: If I have a plotly express map like:
fig = px.scatter_geo(df, lat="lat", lon="lon", color="count", hover_name="text", hover_data=None,
                     size="count", animation_frame="dec", projection="natural earth", size_max = 50)

how do I put a few of them using make_subplots?
I got an error when I tried to.

Thanks for your help so far!

**Comment by nicolaskruchten** [comment] 2019-07-19 19:58
Ah sorry: today you can make a figure with a single map with `px.scatter_geo` *or* a figure with multiple maps with `go.make_subplots` but you can't use them together.

In the future, you'll be able to say `px.scatter_geo(facet_row=, facet_col=)` but that's not supported yet. See this issue: https://github.com/plotly/plotly.py/issues/2646

**Comment by Maxpyt** [comment] 2019-07-24 11:16
> 
> 
> There's no news on composing PX charts like this, but Plotly.py v4 came out this week, and it features a new and much-easier-to-use subplots system! Check it out here https://plot.ly/python/subplots/
> 
> Also, as of this week, Plotly Express is now part of Plotly.py (accessible as `plotly.express`) and is interoperable with the `make_subplots` function described in the link above.

That sounds great! Could you explain how this interoperability works?
When using  
```
fig = make_subplots(rows=2, cols=2)
fig.add_trace(plotly.express.scatter(...),row=1,col=1)
```
it still throws value errors.
Thanks!

**Comment by nicolaskruchten** [comment] 2019-07-24 15:06
Yes, the interoperability actually goes the other way: facetted figures created with `px` can be edited with `fig.add_trace(row=1, col=1)`.

`px.scatter()` returns a full figure rather than a trace, so you cannot pass its output to `add_trace()` on a figure created externally to `px`. 

As I said, we're working on a solution for this kind of thing but we're not there yet :)

See also [Composition](https://github.com/plotly/plotly.py/issues/2647) and [Overlaying](https://github.com/plotly/plotly.py/issues/2648) issues

**Comment by kozmers** [comment] 2019-09-08 04:12
Without concerning the right color bar, the scatters can be realized by adding the fist trace of every figure to subplots:  `add_trace(fig['data'][0])`.
```
fig1 = px.scatter(color='colname1')
fig2 = px.scatter(color='colname2')
trace1 = fig1['data'][0]
trace2 = fig2['data'][0]

fig = make_subplots(rows=2, cols=1)
fig.add_trace(trace1, row=1, col=1)
fig.add_trace(trace2, row=2, col=1)
```

**Comment by vanshika97** [comment] 2020-02-18 13:26
> Yes, you can use `facet_row` and `facet_col` on any 2d-cartesian plot, including those with date axes.

How to create subplots in `px.bar_polar()` where `facet_row` and `facet_col` parameters don't exist?

**Comment by nicolaskruchten** [comment] 2020-02-28 23:00
@vanshika97 we don't yet support facetting for non-cartesian (i.e. polar) subplots. See this tracking issue: https://github.com/plotly/plotly.py/issues/2646

**Comment by mattou78400** [comment] 2020-03-13 16:30
Hey all,

It's been a while, I was wondering whether any fix/update has been found for that?

Thanks!

**Comment by xhuyvn** [comment] 2020-06-27 03:16
Hi all,

Does can I make subplot with plotly express sunburst? It's been a while, but topic did not update solution.
Thanks.

**Comment by nicolaskruchten** [comment] 2020-06-27 11:45
@xhuyvn at the moment we still only support faceting on 2d cartesian functions like scatter, bar, line etc... see this tracking issue: https://github.com/plotly/plotly.py/issues/2646

**Comment by bharathngowda** [comment] 2020-06-27 23:59
How to make n number of subplots in plotly? 
I can achieve the same in Matplotlib as seen in the below example.

In the below example as the length of list 'x' changes the subplots are plotted. We don't define the row and column number for each subplot. Its plotted automatically in the order of the list elements. We define only total rows and cols for the figure only.

import matplotlib.pyplot as plt

x=['Plotly','Express','Dash','Python']

fig,ax=plt.subplots(nrows=int(len(x)/2), ncols=2,figsize=(15,7))

for i,j in zip(ax.flat,x):
    i.bar([x for x in range(5)],[x for x in range(0,100,20)])
    i.set_title(j)
    fig.tight_layout()
plt.show()

**Image as below**

![download](https://user-images.githubusercontent.com/65902027/85934414-840f7c00-b8ff-11ea-828e-c967a5fabb4a.png)

**Comment by set92** [comment] 2020-07-01 23:42
> 
> 
> Without concerning the right color bar, the scatters can be realized by adding the fist trace of every figure to subplots: `add_trace(fig['data'][0])`.
> 
> ```
> fig1 = px.scatter(color='colname1')
> fig2 = px.scatter(color='colname2')
> trace1 = fig1['data'][0]
> trace2 = fig2['data'][0]
> 
> fig = make_subplots(rows=2, cols=1, shared_xaxes=False)
> fig.add_trace(trace1, row=1, col=1)
> fig.add_trace(trace2, row=2, col=1)
> ```

With his help I wrote a method to automate plotting boxplot and violin, for histogram it should be easy but there is some bug.

```python
def facetting_data(df, n_cols=3, to_plot='box'):
    numeric_cols = df.select_dtypes('number').columns
    n_rows = -(-len(numeric_cols) // n_cols)  # math.ceil in a fast way, without import
    row_pos, col_pos = 1, 0
    fig = make_subplots(rows=n_rows, cols=n_cols)

    for col in numeric_cols:
        # trace extracted from the fig
        trace = getattr(px, to_plot)(df[col])["data"][0]
        # auto selecting a position of the grid
        if col_pos == n_cols: row_pos += 1
        col_pos = col_pos + 1 if (col_pos < n_cols) else 1
        # adding trace to the grid
        fig.add_trace(trace, row=row_pos, col=col_pos)
    return fig

fig = facetting_data(data, to_plot='violin')
# final tweaks
fig.update_layout(width=1000, height=800, title='Violin per feature', title_x=0.5)
fig.show()
```

EDIT: For histogram you can use `fig = facetting_data(data.select_dtypes(np.float64), to_plot='histogram')`, at least with my [dataset](https://www.kaggle.com/unsdsn/world-happiness) was failing because a couple int columns (Happiness Rank and Year). Not sure why, but with them it draw the first trace and after that the rest of the traces were almost static.

**Comment by nicolaskruchten** [comment] 2020-07-03 01:37
@set92 it looks like this `facetting_data` function does the same thing as the built-in `facet_row` and `facet_col` arguments of functions like `px.box()` and `px.histogram()` and `px.violin()` to me, no?

In general, folks, I promise I'll post an update on this issue when Plotly Express supports faceting for non-cartesian subplots. We're not working on it in the next couple of months, but we would happily accept a pull request if someone wants to work on it... The main bit of the code that needs modifying is here: https://github.com/plotly/plotly.py/blob/fb84bc52b9f4c424e93402ebfbe7b23502a601f4/packages/python/plotly/plotly/express/_core.py#L2047

**Comment by nicolaskruchten** [comment] 2020-07-03 01:38
@bharathngowda please check out the `facet_col_wrap` option documented here: https://plotly.com/python/facet-plots/#wrapping-column-facets

**Comment by set92** [comment] 2020-07-03 16:50
@nicolaskruchten I think they don't. For what I saw `facet_row`/`facet_col` is to provide a new dimension to divide the data no? The `facetting_data` is much simpler, I made it because I was trying to do an histogram/boxplot.. per feature. If I do it without arguments it will plot all the boxplots in the same graph, which makes hard to see some statistics right away.

For example, the first image is with a direct call, and the second is using the `make_subplots` function to create a individual graph per feature.

Plotly call |  facetting_data function
:-------------------------:|:-------------------------:
<img src="https://user-images.githubusercontent.com/1332249/86485229-81c27d00-bd58-11ea-9eaf-12813eae91dd.png" width="400" height="400"> | <img src="https://user-images.githubusercontent.com/1332249/86485232-82f3aa00-bd58-11ea-9bd9-851902a8afa6.png" width="400" height="400">

**Reproducible example** with scatter+regression plot, since is a little bit different than previous function:
Dataset is [world happiness (42kb)](https://www.dropbox.com/s/b1plqzo6m5f1zdm/World_Happiness_2015_2017_.csv?dl=0), same as in [kaggle](https://www.kaggle.com/unsdsn/world-happiness), but resized.
```python
import plotly.express as px
df = pd.read_csv('World_Happiness_2015_2017_.csv')
px.scatter(df, x=df.select_dtypes(np.float64).columns, y='Happiness Score', trendline='ols')
```
<img src="https://user-images.githubusercontent.com/1332249/86486174-eed71200-bd5a-11ea-8a54-595c5d88bf35.png" width="500" height="400">

And with the function, that updated to work with 2 traces per graph is:
```python
def facetting_scatter_plot(df, n_cols=3, y='Happiness Score'):
    numeric_cols = df.select_dtypes('number').columns
    n_rows = -(-len(numeric_cols) // n_cols)  # math.ceil in a fast way, without import
    row_pos, col_pos = 1, 0
    fig = make_subplots(rows=n_rows, cols=n_cols, subplot_titles=numeric_cols)

    for col in numeric_cols:
        # trace extracted from the fig
        trace = px.scatter(df, x=col, y=y, trendline='ols', trendline_color_override='#DC143C')["data"]
        # auto selecting a position of the grid
        if col_pos == n_cols: row_pos += 1
        col_pos = col_pos + 1 if (col_pos < n_cols) else 1
        # adding trace to the grid
        fig.add_trace(trace[0], row=row_pos, col=col_pos)
        fig.add_trace(trace[1], row=row_pos, col=col_pos)
    return fig

fig = facetting_scatter_plot(data.select_dtypes(np.float64))
# final tweaks
fig.update_layout(width=1000, height=800, title='% of variation in Happiness Score explained by each feature', title_x=0.5)
fig.show()
```
And it returns:
<img src="https://user-images.githubusercontent.com/1332249/86486302-3067bd00-bd5b-11ea-88c1-9a1081356a77.png" width="500" height="400">
Probably it doesn't make much sense since you can zoom in, resize... but with boxplot happens the same as with histogram, each feature is too different from the rest so they fit better in individual graphs, and if I do a call per feature they would take a larger space.

**Comment by nicolaskruchten** [comment] 2020-07-03 18:08
You can do almost the same thing with

```python
px.scatter(df, x=df.select_dtypes(np.float64).columns, y='Happiness Score', trendline='ols',
          facet_col="variable", facet_col_wrap=3).update_xaxes(matches=None)
```

**Comment by nicolaskruchten** [comment] 2020-07-16 20:34
This issue is kind of branching off into various directions so I've created a few different issues to track different parts of it, as well as worked to clarify our documentation (links below) so I'm going to close it and lock it now.

Tracking issues:
* Non-cartesian faceting: https://github.com/plotly/plotly.py/issues/2646
* Figure composition (side by side, vertical): https://github.com/plotly/plotly.py/issues/2647
* Figure overlay (on top of): https://github.com/plotly/plotly.py/issues/2648

Documentation:
* [Plotly Express facets](https://plotly.com/python/facet-plots/)
* [Plotly Express marginal plots](https://plotly.com/python/marginal-plots/)
* [Arbitrary subplots](https://plotly.com/python/subplots/)
* [Mixed subplots](https://plotly.com/python/mixed-subplots/)
* [Mixing trace types in a single plot](https://plotly.com/python/graphing-multiple-chart-types/)
* [The Figure Data Structure, where all this stuff is configured](https://plotly.com/python/figure-structure/)

**Closed by nicolaskruchten** 2020-07-16 20:34 UTC
