### ISSUE TITLE
px.histogram log_x argument doesn't plot

### ISSUE THREAD

**Issue by awalther** [plotly/plotly_express#86] opened 2019-05-16 08:51 UTC
Minimal example below (added `marginal=rug` to show where the bars supposedly should land): 

```
import plotly_express as px

fig = px.histogram(
    px.data.iris(), 
    x='petal_width',
    color='species',
    log_x=True,
    marginal='rug',
)
fig

**Comment by nicolaskruchten** [comment] 2019-05-20 19:01
This is currently a limitation of Plotly.js: https://github.com/plotly/plotly.js/issues/1844

When it's fixed there, it will be fixed here automatically :)

**Comment by achraf-o** [comment] 2020-04-05 10:24
Is there a fix for this situation. I am experiencing the same issue

**Comment by nicolaskruchten** [comment] 2020-10-19 23:07
Closing as dupe of https://github.com/plotly/plotly.js/issues/1844

**Closed by nicolaskruchten** 2020-10-19 23:07 UTC
